baseURL = "https://objective-bohr-30071a.netlify.app/"  
languageCode = "en-us"
title = "302_group6"
theme = "ananke"

[build]
publish = "public"
command = "hugo --gc --minify"

#menu links
[[menu.main]]
  name = "Home"
  weight = 1
  url = "/Home.html"
  
[[menu.main]]
  name = "Menu"
  weight = 2
  url = "/Menu.html"
 
[[menu.main]]
  name = "Order"
  weight = 3
  url = "/Order.html"

[[menu.main]]
  name = "About"
  weight = 4
  url = "/About.html"

[[menu.main]]
  name = "Contact"
  weight = 5
  url = "/Contact.html"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

